### ISSUE TITLE
Error with unlink cache shows up on map explorer is info is clicked

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#167] opened 2016-08-26 08:15 UTC
Warning
: unlink(/cache/): Is a directory in /var/www/html/wp-content/plugins/wpckan/utils/datastore-api.php on line 19

![img_26082016_150604](https://cloud.githubusercontent.com/assets/6613530/17998689/dd67b29c-6b9f-11e6-8967-467c8feddc09.png)

**Comment by acorbi** [comment] 2016-10-23 04:35
@Huyeng I could not reproduce this issue. Im closing it. please re-open if reappears

**Closed by acorbi** 2016-10-23 04:35 UTC
