### ISSUE TITLE
Add related dataset is stopped working any more

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wpckan#263] opened 2017-03-27 07:40 UTC
There is a list of the related dataset  on Topic post type once typing the keywords in the metabox of related dataset before, but not it is not working. 
https://opendevelopmentcambodia.net/wp-admin/post-new.php?post_type=topic

![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/24345648/49dbc352-12fb-11e7-8dd2-a4c68e6c4366.jpg)

**Comment by acorbi** [comment] 2017-03-27 09:44
@Huyeng apparently the ckan instance does not have CORS enabled or is not properly configured. Im checking the config now.

![screenshot from 2017-03-27 11-43-46](https://cloud.githubusercontent.com/assets/384894/24350504/bb754830-12e2-11e7-954c-1db4d3b48881.png)

**Comment by acorbi** [comment] 2017-03-27 09:59
@Huyeng I have just checked the CKAN config and looks correct. The problem seems to be caused by the fact that the CKAN instance is being addressed via https://data.opendevelopmentcambodia.net which causes the Cross-domain issue. I'm going to ping proteus and ask if they can solve it on the DNS side.

**Comment by acorbi** [comment] 2017-03-27 10:30
fixed now. please test

**Closed by acorbi** 2017-03-27 10:30 UTC
