### ISSUE TITLE
Cannot publish dataset on CKAN

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#343] opened 2017-12-21 04:45 UTC
The published dataset became in private status after I update the metadata of its. The problem is about the visible status on CKAN "no word publish". Here is the link to the dataset: https://data.opendevelopmentmekong.net/dataset/edit/protectedareas

![image](https://user-images.githubusercontent.com/18112596/34240916-3d0b7a60-e644-11e7-9e67-ebb83cfa3346.png)

**Comment by acorbi** [comment] 2017-12-21 09:47
@punwath **vetting process** on CKAN has now been re-enabled as indicated on https://wiki.opendevelopmentmekong.net/partners:content_review.

In order to publish a record, an admin needs to review it and close/delete the latest **Issue** assigned to the  dataset. please read the guide linked above.

Im closing this Issue since this is the expected behaviour.

**Comment by Huyeng** [comment] 2017-12-23 09:08
No, there is no issue opened. However, the admin role (not admin user) can't select the option "Public"of visibility, as it has only one option "Private". When I login with the admin user, then the dataset  can be pulished. 

![screenshot_2](https://user-images.githubusercontent.com/6613530/34318491-8a2205b8-e7fb-11e7-81ca-0673f9c550cf.jpg)

**Comment by Huyeng** [comment] 2017-12-23 09:10
No, there is no issue opened. However, the admin role (not admin user) can't select the option "Public"of visibility, as it has only one option "Private". When I login with the admin user, then the dataset  can be pulished. 

![Uploading Screenshot_2.jpg…]()

**Comment by acorbi** [comment] 2017-12-23 10:46
@Huyeng I have tweaked the code so now:

- Organization admins can set the visibility to **Private/Public**  using the dropdown box
- This dropdown box is hidden to non-admin users (cannot publish/unpublish records)
- When a dataset is created, a default issue is created too. In order to publishing a record, an admin user needs to close/delete this issue as indicated in https://wiki.opendevelopmentmekong.net/partners:content_review

**Comment by Huyeng** [comment] 2017-12-24 07:23
I have some question regarding to this:
- Who are the admin user that you mentioned here? is it referred to username "admin" or someone who have admin role? If referred to any username which is admin role, so the current implement is not correctly because my username huyeng is admin role, but I can't see the visibility dropbox (see the screenshot), but I can see with admin username. Please clarify on this.
<img width="624" alt="screenshot at dec 24 14-13-38" src="https://user-images.githubusercontent.com/6613530/34324918-ba00de3a-e8b4-11e7-8070-dc6be0bd6201.png">

- What will happen if the editor users update the published dataset, will be private, to still publish after updating?

- When this implemented? It should be have a discussion and agreement first before implement, otherwise, it affect to our work. You may not know that our team promised with our donor to publish a number of records, however, the editors who have the admin right can't publish, and a number of published records were changed to be private and disappeared on the site which were question from donor and users. 
<img width="273" alt="screenshot at dec 24 14-22-40" src="https://user-images.githubusercontent.com/6613530/34324948-ee22bbec-e8b5-11e7-9a3d-5ea53474ade7.png">

**Comment by acorbi** [comment] 2017-12-24 11:52
> Who are the admin user that you mentioned here? is it referred to username "admin" or someone who have admin role? If referred to any username which is admin role, so the current implement is not correctly because my username huyeng is admin role, but I can't see the visibility dropbox (see the screenshot), but I can see with admin username. Please clarify on this.

Thanks for raising this. I made a mistake in my statement since this field is only visible for users with the **sysadmin** role (See http://docs.ckan.org/en/latest/maintaining/paster.html?highlight=sysadmin#sysadmin-give-sysadmin-rights). I have given your username **huyeng** now sysadmin rights, so you should be able to see this field.

# HOWEVER

In general, you do not need, and you should not, publish records by setting them to public. The procedure described on https://wiki.opendevelopmentmekong.net/partners:content_review should be followed. 

I know there are some records which are currently private and do not have any entry on the **issues** tab, therefore, in order to publish them following the guide. You, or any other admin, would need to create an issue and delete it straight away, that way the record will be automatically published.

> What will happen if the editor users update the published dataset, will be private, to still publish after updating?

It will be keep its current status. editors cannot change the visibility of a record (unless they create an issue)

>

**Closed** 2018-01-12 13:49 UTC

**Comment by prustar** [comment] 2018-01-14 11:05
@Huyeng @acorbi -- Glad to see that this issue has finally been resolved and that the feature which was initiated sometime ago is now fully implemented. It will help to ensure that all datasets are actually vetted appropriately and improve the standards for publications. This issue is linked to a new one which was raised recently that Editors need to be able to raise new issues but not delete them. 

@Huyeng -- just to note and address your concern that this feature was not discussed previously. It was in fact a mechanism implemented to improve the number of erroneous records being uploaded into CKAN and ensure accuracy and standards prior to publishing. This was as a result of the realisation that the auto import of records from Gen I created so many incomplete records which didn't meet standards.  It was discussed at length with Chandra and Try at the time of implementation, the wiki guide was drafted and the ODC team should have been following these guidelines with Chandara as the senior administrator for your team. The team at ODC has changed somewhat since then but I am pretty sure that the remaining staff were aware of this protocol although I'm not sure who actually replaced Chandara's role as senior administrator. It's unfortunate that there was a delay in finalising this feature to function accordingly but it's fixed now so we should not have any more problems.
