### ISSUE TITLE
[CKAN-LIBRARY]---Bilingual Field: Corporate Author

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/wpckan#231] opened 2017-01-30 04:25 UTC
Bilingual field for "corporate author" and "year of publication" did not work, since its record metadata is shown as one page.

For the concerned record: https://data.opendevelopmentmekong.net/en/library_record/key-findings-of-the-mrcs-strategic-environmental-assessment-on-mekong-mainstream-dams

**Comment by ChandaraKhun** [comment] 2017-01-30 04:30
With this particular record, the language in the record resources that is shown on Khmer remains English; So, I am curious if it does also happen with the metadata of the resource document as well.

**Comment by acorbi** [comment] 2017-01-30 14:04
@ChandaraKhun thanks for your input. Some comments:

1. Please be more clear while describing the issues you raise. Please follow the instructions available on https://wiki.opendevelopmentmekong.net/public:bug_reporting and indicate concrete steps to reproduce the issue. "did not work" is not descriptive and leads to confusion.

2. **Author (corporate)*+ and **Publication date** are **NOT multilingual** fields as specified on https://wiki.opendevelopmentmekong.net/public:metadata . If you would like to suggest to make them multilingual, please coordinate with @prustar 

3. I do not completely understand your second comment but in case you mean that the resource's title and description are shown in English even if the Khmer language is selected on CKAN, that is the expected behaviopur because the resource is not translated yet, only english information has been specified: https://data.opendevelopmentmekong.net/api/3/action/package_show?id=key-findings-of-the-mrcs-strategic-environmental-assessment-on-mekong-mainstream-dams

**Comment by acorbi** [comment] 2017-02-28 15:54
@ChandaraKhun I'm closing this Issue since I believe it is invalid. please re-open if you consider.

**Closed by acorbi** 2017-02-28 15:54 UTC
